version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    env_file:
      - .env
    volumes:
      - .:/src
    depends_on:
      - db
    ports:
      - 8080:8000

  db:
    image: mongo:latest
    env_file:
      - .env
    ports:
      - 37017:27017
    restart: on-failure