site_name: Arrest
site_author: Shiladitya Bose

theme:
  name: material

  palette:

      # Palette toggle for light mode
      - media: "(prefers-color-scheme: light)"
        scheme: default
        primary: purple
        accent: light purple
        toggle:
          # icon: material/lightbulb
          icon: material/brightness-4
          name: Switch to dark mode

      # Palette toggle for dark mode
      - media: "(prefers-color-scheme: dark)"
        scheme: slate
        primary: deep purple
        accent: purple
        toggle:
          # icon: material/lightbulb-outline
          icon: material/brightness-7
          name: Switch to light mode

  features:
    - navigation.sections

nav:
  - Introduction: index.md
  - Getting Started:
    - getting-started.md
    - Making a request: making-a-request.md
  - API Documentation: api.md

markdown_extensions:
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: false
  - attr_list

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            heading_level: 4
            merge_init_into_class: true
