# generated by datamodel-codegen:
#   filename:  <stdin>
#   timestamp: 2024-01-25T19:40:23+00:00

from __future__ import annotations

from enum import Enum
from typing import List, Optional

from pydantic import AwareDatetime, BaseModel, Field


class Status(Enum):
    placed = 'placed'
    approved = 'approved'
    delivered = 'delivered'


class Order(BaseModel):
    id: Optional[int] = Field(None, examples=[10])
    petId: Optional[int] = Field(None, examples=[198772])
    quantity: Optional[int] = Field(None, examples=[7])
    shipDate: Optional[AwareDatetime] = None
    status: Optional[Status] = Field(None, description='Order Status', examples=['approved'])
    complete: Optional[bool] = None


class Address(BaseModel):
    street: Optional[str] = Field(None, examples=['437 Lytton'])
    city: Optional[str] = Field(None, examples=['Palo Alto'])
    state: Optional[str] = Field(None, examples=['CA'])
    zip: Optional[str] = Field(None, examples=['94301'])


class Category(BaseModel):
    id: Optional[int] = Field(None, examples=[1])
    name: Optional[str] = Field(None, examples=['Dogs'])


class User(BaseModel):
    id: Optional[int] = Field(None, examples=[10])
    username: Optional[str] = Field(None, examples=['theUser'])
    firstName: Optional[str] = Field(None, examples=['John'])
    lastName: Optional[str] = Field(None, examples=['James'])
    email: Optional[str] = Field(None, examples=['john@email.com'])
    password: Optional[str] = Field(None, examples=['12345'])
    phone: Optional[str] = Field(None, examples=['12345'])
    userStatus: Optional[int] = Field(None, description='User Status', examples=[1])


class Tag(BaseModel):
    id: Optional[int] = None
    name: Optional[str] = None


class Status1(Enum):
    available = 'available'
    pending = 'pending'
    sold = 'sold'


class Pet(BaseModel):
    id: Optional[int] = Field(None, examples=[10])
    name: str = Field(..., examples=['doggie'])
    category: Optional[Category] = None
    photoUrls: List[str]
    tags: Optional[List[Tag]] = None
    status: Optional[Status1] = Field(None, description='pet status in the store')


class ApiResponse(BaseModel):
    code: Optional[int] = None
    type: Optional[str] = None
    message: Optional[str] = None


class Customer(BaseModel):
    id: Optional[int] = Field(None, examples=[100000])
    username: Optional[str] = Field(None, examples=['fehguy'])
    address: Optional[List[Address]] = None
