name: Release

on:
  release:
    types: [published]

jobs:
  publish:
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.10']
        poetry-version: ['1.4.2']
        os: ['ubuntu-latest']

    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install poetry
      uses:  abatilo/actions-poetry@v2
      with:
          poetry-version: ${{ matrix.poetry-version }}
    - name: Build
      run: poetry build
    - name: Publish
      env:
        PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
      run: |
        poetry config pypi-token.pypi $PYPI_TOKEN
        poetry publish
    - name: Install dependencies
      run: poetry install --with docs
    - name: Build docs
      run: poetry run mkdocs build -f -
    - name: Publish Docs
      run: poetry run mkdocs gh-deploy
