name: Tests

on:
  push:
    branches:
      - "master"

  pull_request:
    types:
      - opened
    branches:
      - master

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.10', '3.11']
        poetry-version: ['1.4.2']
        os: ['ubuntu-latest', 'windows-latest']

    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install poetry
      uses:  abatilo/actions-poetry@v2
      with:
          poetry-version: ${{ matrix.poetry-version }}

    - name: Install dependencies
      run: poetry install

    - name: Upgrade pip
      run: poetry run pip install --upgrade pip

    - name: Run Tests
      run: poetry run pytest --cov=arrest --cov-report=term-missing --cov-report=html --cov-report=xml
    - name: Run black
      run: poetry run black . --check
    - name: Run isort
      run: poetry run isort . --check-only --profile black
    - name: Run flake8
      run: poetry run flake8 .
    - name: Run bandit
      run: poetry run bandit .
    - name: Run saftey
      run: poetry run safety check

    - name: Codecov coverage
      uses: codecov/codecov-action@v3
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
