name: Tests

on:
  push:
    branches:
      - "master"

  pull_request:
    branches:
      - master

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11"]
        os: ["ubuntu-latest", "windows-latest"]

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Set up Python
        run: uv python install ${{ matrix.python-version }}

      - name: Install dependencies
        run: uv sync --all-extras --all-groups

      - name: Run ruff
        run: uv run ruff check . && uv run ruff format --check

      - name: Run bandit
        run: uv run bandit .

      - name: Run safety
        if: runner.os != 'Windows'
        uses: pyupio/safety-action@v1
        with:
          api-key: ${{ secrets.SAFETY_API_KEY }}

      - name: Run Tests
        run: bash ./scripts/coverage.sh

      - name: Run Coverage xml
        run: |
          uv run coverage report --show-missing
          uv run coverage xml

      - name: Codecov coverage
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
